name: OpenAPI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  vacuum-lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Formatting
        run: npx prettier --check topsort-api-v2.yml

      - name: Validate with Vacuum
        uses: pb33f/vacuum-action@v2
        with:
          openapi_path: "topsort-api-v2.yml"
          github_token: ${{ secrets.GITHUB_TOKEN }}
